In [9]:
import pandas as pd
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderTimedOut

In [10]:
# Função para obter latitude e longitude a partir de endereço ou CEP
def get_lat_long(query):
    geolocator = Nominatim(user_agent="nome_do_seu_projeto_geocoding")
    try:
        location = geolocator.geocode(query, timeout=10)
        if location:
            return (location.latitude, location.longitude)
        else:
            return (None, None)
    except GeocoderTimedOut:
        return (None, None)

In [11]:
data = {
    'endereco': ['Rua Exemplo 123', None, 'Av Paulista 1000', None],
    'cep': [None, '01000-000', None, '01310-200']
}
df = pd.DataFrame(data)

In [12]:
display(df)

           endereco        cep
0   Rua Exemplo 123       None
1              None  01000-000
2  Av Paulista 1000       None
3              None  01310-200

In [13]:
def preencher_lat_long(row):
    if pd.notnull(row['endereco']):
        return get_lat_long(row['endereco'])
    elif pd.notnull(row['cep']):
        return get_lat_long(row['cep'])
    else:
        return (None, None)

In [14]:

# Aplicando a função ao DataFrame para obter latitude e longitude
df[['latitude', 'longitude']] = df.apply(preencher_lat_long, axis=1, result_type="expand")
display(df)

           endereco        cep   latitude  longitude
0   Rua Exemplo 123       None -30.268570 -54.069447
1              None  01000-000  46.220176   5.246330
2  Av Paulista 1000       None -23.564887 -46.651918
3              None  01310-200 -23.220138 -46.402062